import { ToolType } from "$lib/types/ToolType"

export const TOOL_ICONS: Record<ToolType, string> = {
	[ToolType.BLUE_DRUIDS_EYE]: "01_druids_eye.png",
    [ToolType.BLUE_DRUIDS_EYES]: "02_druids_eyes.png",
    [ToolType.BLUE_MAGMA_BELL]: "03_magma_bell.png",
    [ToolType.BLUE_WARDING_BELL]: "04_warding_bell.png",
    [ToolType.BLUE_POLLIP_POUCH]: "05_pollip_pouch.png",
    [ToolType.BLUE_FRACTUED_MASK]: "06_fractued_mask.png",
    [ToolType.BLUE_MULTIBINDER]: "07_multibinder.png",
    [ToolType.BLUE_WEAVELIGHT]: "08_weavelight.png",
    [ToolType.BLUE_SAWTOOTH_CIRCLET]: "09_sawtooth_circlet.png",
    [ToolType.BLUE_INJECTOR_BAND]: "10_injector_band.png",
    [ToolType.BLUE_SPOOL_EXTENDER]: "11_spool_extender.png",
    [ToolType.BLUE_RESERVE_BIND]: "12_reserve_bind.png",
    [ToolType.BLUE_CLAW_MIRROR]: "13_claw_mirror.png",
    [ToolType.BLUE_CLAW_MIRRORS]: "15_claw_mirrors.png",
    [ToolType.BLUE_MEMORY_CRYSTAL]: "16_memory_crystal.png",
    [ToolType.BLUE_SNITCH_PICK]: "17_snitch_pick.png",
    [ToolType.BLUE_VOLT_FILAMENT]: "18_volt_filament.png",
    [ToolType.BLUE_QUICK_SLING]: "19_quick_sling.png",
    [ToolType.BLUE_WREATH_OF_PURITY]: "20_wreath_of_purity.png",
    [ToolType.BLUE_LONGCLAW]: "21_longclaw.png",
    [ToolType.BLUE_WISPFIRE_LANTERN]: "22_wispfire_lantern.png",
    [ToolType.BLUE_EGG_OF_FLEALIA]: "23_egg_of_flealia.png",
    [ToolType.BLUE_PIN_BADGE]: "24_pin_badge.png",

    [ToolType.RED_STRAIGHT_PIN]: "01_straight_pin.png",
    [ToolType.RED_THREEFOLD_PIN]: "02_threefold_pin.png",
    [ToolType.RED_STRING_SHARD]: "03_string_shard.png",
    [ToolType.RED_TACKS]: "04_tacks.png",
    [ToolType.RED_LONGPIN]: "05_longpin.png",
    [ToolType.RED_CURVECLAW]: "06_curveclaw.png",
    [ToolType.RED_CURVESICKLE]: "07_curvesickle.png",
    [ToolType.RED_THROWING_RING]: "08_throwing_ring.png",
    [ToolType.RED_PIMPILO]: "09_pimpilo.png",
    [ToolType.RED_CONCHCUTTER]: "10_conchcutter.png",
    [ToolType.RED_SILKSHOT_ORIGINAL]: "11_silkshot_original.png",
    [ToolType.RED_SILKSHOT_TWELVE]: "12_silkshot_twelve.png",
    [ToolType.RED_SILKSHOT_FORGE]: "13_silkshot_forge.png",
    [ToolType.RED_DELVERS_DRILL]: "14_delvers_drill.png",
    [ToolType.RED_COGWORK_WHEEL]: "15_cogwork_wheel.png",
    [ToolType.RED_COGFLY]: "16_cogfly.png",
    [ToolType.RED_ROSARY_CANNON]: "17_rosary_cannon.png",
    [ToolType.RED_VOLT_VESSEL_SPEAR]: "18_volt_vessel_spear.png",
    [ToolType.RED_VOLT_VESSEL_BOLA]: "19_volt_vessel_bola.png",
    [ToolType.RED_FLINTSLATE]: "20_flintslate.png",
    [ToolType.RED_SNARE_SETTER]: "21_snare_setter.png",
    [ToolType.RED_FLEA_BREW]: "22_flea_brew.png",
    [ToolType.RED_PLASMIUM_PHIAL]: "23_plasmium_phial.png",
    [ToolType.RED_NEEDLE_PHIAL]: "24_needle_phial.png",

    [ToolType.YELLOW_COMPASS]: "01_compass.png",
    [ToolType.YELLOW_SHARD_PENDANT]: "02_shard_pendant.png",
    [ToolType.YELLOW_MAGNETIC_BROOCH]: "03_magnetic_brooch.png",
    [ToolType.YELLOW_WEIGHTED_BELT]: "04_weighted_belt.png",
    [ToolType.YELLOW_BARBED_BRACELET]: "05_barbed_bracelet.png",
    [ToolType.YELLOW_DEAD_BUGS_PURSE]: "06_dead_bugs_purse.png",
    [ToolType.YELLOW_SHELL_SATCHEL]: "07_shell_satchel.png",
    [ToolType.YELLOW_MAGNETITE_DICE]: "08_magnetite_dice.png",
    [ToolType.YELLOW_SCUTTLE_BRACE]: "09_scuttle_brace.png",
    [ToolType.YELLOW_ASCENDANTS_GRIP]: "10_ascendants_grip.png",
    [ToolType.YELLOW_SPIDER_STRINGS]: "11_spider_strings.png",
    [ToolType.YELLOW_SILKSPEED_ANKLETS]: "12_silkspeed_anklets.png",
    [ToolType.YELLOW_THIEFS_MARK]: "13_thiefs_mark.png",
};