import { ToolType } from "../enums/ToolType";

export const TOOLS_WITH_DAMAGE: ToolType[] = [
    ToolType.StraightPin,
    ToolType.ThreefoldPin,
    ToolType.StringShard,
    ToolType.Tacks,
    ToolType.Longpin,
    ToolType.Curveclaw,
    ToolType.Curvesickle,
    ToolType.ThrowingRing,
    ToolType.Pimpilo,
    ToolType.Conchcutter,
    ToolType.SilkshotOriginal,
    ToolType.SilkshotTwelve,
    ToolType.SilkshotForge,
    ToolType.DelversDrill,
    ToolType.CogworkWheel,
    ToolType.Cogfly,
    ToolType.RosaryCannon,
    ToolType.VoltVesselSpear,
    ToolType.VoltVesselBola,
    ToolType.Flintslate,
    ToolType.SnareSetter,
    ToolType.FleaBrew,
    ToolType.NeedlePhial,
    ToolType.WardingBell,
    ToolType.PollipPouch,
    ToolType.SawtoothCirclet,
    ToolType.ClawMirror,
    ToolType.ClawMirrors,
    ToolType.MemoryCrystal,
    ToolType.WispfireLantern,
] as const;