import { ToolType } from "../enums/ToolType"

const base = "assets/tools/";
const redPath = "red/";
const bluePath = "blue/";
const yellowPath = "yellow/";

export const TOOL_ICONS: Record<ToolType, string> = {
    [ToolType.DruidsEye]: base + bluePath + "01_druids_eye.png", 
    [ToolType.DruidsEyes]: base + bluePath + "02_druids_eyes.png", 
    [ToolType.MagmaBell]: base + bluePath + "03_magma_bell.png", 
    [ToolType.WardingBell]: base + bluePath + "04_warding_bell.png", 
    [ToolType.PollipPouch]: base + bluePath + "05_pollip_pouch.png", 
    [ToolType.FractuedMask]: base + bluePath + "06_fractued_mask.png", 
    [ToolType.Multibinder]: base + bluePath + "07_multibinder.png", 
    [ToolType.Weavelight]: base + bluePath + "08_weavelight.png", 
    [ToolType.SawtoothCirclet]: base + bluePath + "09_sawtooth_circlet.png", 
    [ToolType.InjectorBand]: base + bluePath + "10_injector_band.png", 
    [ToolType.SpoolExtender]: base + bluePath + "11_spool_extender.png", 
    [ToolType.ReserveBind]: base + bluePath + "12_reserve_bind.png", 
    [ToolType.ClawMirror]: base + bluePath + "13_claw_mirror.png", 
    [ToolType.ClawMirrors]: base + bluePath + "15_claw_mirrors.png", 
    [ToolType.MemoryCrystal]: base + bluePath + "16_memory_crystal.png", 
    [ToolType.SnitchPick]: base + bluePath + "17_snitch_pick.png", 
    [ToolType.VoltFilament]: base + bluePath + "18_volt_filament.png", 
    [ToolType.QuickSling]: base + bluePath + "19_quick_sling.png", 
    [ToolType.WreathOfPurity]: base + bluePath + "20_wreath_of_purity.png", 
    [ToolType.Longclaw]: base + bluePath + "21_longclaw.png", 
    [ToolType.WispfireLantern]: base + bluePath + "22_wispfire_lantern.png", 
    [ToolType.EggOfFlealia]: base + bluePath + "23_egg_of_flealia.png", 
    [ToolType.PinBadge]: base + bluePath + "24_pin_badge.png", 

    [ToolType.StraightPin]: base + redPath + "01_straight_pin.png", 
    [ToolType.ThreefoldPin]: base + redPath + "02_threefold_pin.png", 
    [ToolType.StringShard]: base + redPath + "03_string_shard.png", 
    [ToolType.Tacks]: base + redPath + "04_tacks.png", 
    [ToolType.Longpin]: base + redPath + "05_longpin.png", 
    [ToolType.Curveclaw]: base + redPath + "06_curveclaw.png", 
    [ToolType.Curvesickle]: base + redPath + "07_curvesickle.png", 
    [ToolType.ThrowingRing]: base + redPath + "08_throwing_ring.png", 
    [ToolType.Pimpilo]: base + redPath + "09_pimpilo.png", 
    [ToolType.Conchcutter]: base + redPath + "10_conchcutter.png", 
    [ToolType.SilkshotOriginal]: base + redPath + "11_silkshot_original.png", 
    [ToolType.SilkshotTwelve]: base + redPath + "12_silkshot_twelve.png", 
    [ToolType.SilkshotForge]: base + redPath + "13_silkshot_forge.png", 
    [ToolType.DelversDrill]: base + redPath + "14_delvers_drill.png", 
    [ToolType.CogworkWheel]: base + redPath + "15_cogwork_wheel.png", 
    [ToolType.Cogfly]: base + redPath + "16_cogfly.png", 
    [ToolType.RosaryCannon]: base + redPath + "17_rosary_cannon.png", 
    [ToolType.VoltVesselSpear]: base + redPath + "18_volt_vessel_spear.png", 
    [ToolType.VoltVesselBola]: base + redPath + "19_volt_vessel_bola.png", 
    [ToolType.Flintslate]: base + redPath + "20_flintslate.png", 
    [ToolType.SnareSetter]: base + redPath + "21_snare_setter.png", 
    [ToolType.FleaBrew]: base + redPath + "22_flea_brew.png", 
    [ToolType.PlasmiumPhial]: base + redPath + "23_plasmium_phial.png", 
    [ToolType.NeedlePhial]: base + redPath + "24_needle_phial.png", 

    [ToolType.Compass]: base + yellowPath + "01_compass.png", 
    [ToolType.ShardPendant]: base + yellowPath + "02_shard_pendant.png", 
    [ToolType.MagneticBrooch]: base + yellowPath + "03_magnetic_brooch.png", 
    [ToolType.WeightedBelt]: base + yellowPath + "04_weighted_belt.png", 
    [ToolType.BarbedBracelet]: base + yellowPath + "05_barbed_bracelet.png", 
    [ToolType.DeadBugsPurse]: base + yellowPath + "06_dead_bugs_purse.png", 
    [ToolType.ShellSatchel]: base + yellowPath + "07_shell_satchel.png", 
    [ToolType.MagnetiteDice]: base + yellowPath + "08_magnetite_dice.png", 
    [ToolType.ScuttleBrace]: base + yellowPath + "09_scuttle_brace.png", 
    [ToolType.AscendantsGrip]: base + yellowPath + "10_ascendants_grip.png", 
    [ToolType.SpiderStrings]: base + yellowPath + "11_spider_strings.png", 
    [ToolType.SilkspeedAnklets]: base + yellowPath + "12_silkspeed_anklets.png", 
    [ToolType.ThiefsMark]: base + yellowPath + "13_thiefs_mark.png", 
};