import { ToolType } from "$lib/types/ToolType";

export const TOOLS_BLUE = [
    ToolType.BLUE_DRUIDS_EYE,
    ToolType.BLUE_DRUIDS_EYES,
    ToolType.BLUE_MAGMA_BELL,
    ToolType.BLUE_WARDING_BELL,
    ToolType.BLUE_POLLIP_POUCH,
    ToolType.BLUE_FRACTUED_MASK,
    ToolType.BLUE_MULTIBINDER,
    ToolType.BLUE_WEAVELIGHT,
    ToolType.BLUE_SAWTOOTH_CIRCLET,
    ToolType.BLUE_INJECTOR_BAND,
    ToolType.BLUE_SPOOL_EXTENDER,
    ToolType.BLUE_RESERVE_BIND,
    ToolType.BLUE_CLAW_MIRROR,
    ToolType.BLUE_CLAW_MIRRORS,
    ToolType.BLUE_MEMORY_CRYSTAL,
    ToolType.BLUE_SNITCH_PICK,
    ToolType.BLUE_VOLT_FILAMENT,
    ToolType.BLUE_QUICK_SLING,
    ToolType.BLUE_WREATH_OF_PURITY,
    ToolType.BLUE_LONGCLAW,
    ToolType.BLUE_WISPFIRE_LANTERN,
    ToolType.BLUE_EGG_OF_FLEALIA,
    ToolType.BLUE_PIN_BADGE,
] as const;