import { ToolType } from "../enums/ToolType";

export const TOOLS_BLUE: ToolType[] = [
    ToolType.DruidsEye,
    ToolType.DruidsEyes,
    ToolType.MagmaBell,
    ToolType.WardingBell,
    ToolType.PollipPouch,
    ToolType.FractuedMask,
    ToolType.Multibinder,
    ToolType.Weavelight,
    ToolType.SawtoothCirclet,
    ToolType.InjectorBand,
    ToolType.SpoolExtender,
    ToolType.ReserveBind,
    ToolType.ClawMirror,
    ToolType.ClawMirrors,
    ToolType.MemoryCrystal,
    ToolType.SnitchPick,
    ToolType.VoltFilament,
    ToolType.QuickSling,
    ToolType.WreathOfPurity,
    ToolType.Longclaw,
    ToolType.WispfireLantern,
    ToolType.EggOfFlealia,
    ToolType.PinBadge,
] as const;