export enum ToolType {
    // Blue Tools
    DruidsEye,
    DruidsEyes,
    MagmaBell,
    WardingBell,
    PollipPouch,
    FractuedMask,
    Multibinder,
    Weavelight,
    SawtoothCirclet,
    InjectorBand,
    SpoolExtender,
    ReserveBind,
    ClawMirror,
    ClawMirrors,
    MemoryCrystal,
    SnitchPick,
    VoltFilament,
    QuickSling,
    WreathOfPurity,
    Longclaw,
    WispfireLantern,
    EggOfFlealia,
    PinBadge,

    // Red Tools
    StraightPin,
    ThreefoldPin,
    StringShard,
    Tacks,
    Longpin,
    Curveclaw,
    Curvesickle,
    ThrowingRing,
    Pimpilo,
    Conchcutter,
    SilkshotOriginal,
    SilkshotTwelve,
    SilkshotForge,
    DelversDrill,
    CogworkWheel,
    Cogfly,
    RosaryCannon,
    VoltVesselSpear,
    VoltVesselBola,
    Flintslate,
    SnareSetter,
    FleaBrew,
    PlasmiumPhial,
    NeedlePhial,

    // Yellow Tools
    Compass,
    ShardPendant,
    MagneticBrooch,
    WeightedBelt,
    BarbedBracelet,
    DeadBugsPurse,
    ShellSatchel,
    MagnetiteDice,
    ScuttleBrace,
    AscendantsGrip,
    SpiderStrings,
    SilkspeedAnklets,
    ThiefsMark,
};



